name: Dockerized MLOps Pipeline

on: [push]

jobs:
  dockerized-mlops-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Week_8_serverless
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install DVC
        run: pip install dvc dvc_s3

      - name: Pull DVC Files
        run: |
          dvc init --no-scm -f
          dvc remote add -d model-store s3://basicmlops/dvcstore
          dvc pull dvcfiles/trained_model.dvc
          dvc pull dvcfiles/*  # If you have additional DVC-managed files

      - name: Build container
        run: | 
          docker build --build-arg AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
                       --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                       --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                       --tag mlops-basics .
      - name: Push2ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1 
          image: mlops-basics:latest
      - name: Update lambda with image
        run: aws lambda update-function-code --function-name MLOPs-Basics --image-uri 708204279072.dkr.ecr.us-east-1.amazonaws.com/mlops-basics:latest 